### ISSUE TITLE
No image on /m100_x3/image_raw through ssh

### ISSUE THREAD

**Issue by andre-nguyen** [groundmelon/m100_x3#2]
Hi @groundmelon,

after launching the node manually through ssh I can get the image in DJI GO app but the ros topic is empty onboard the manifold:

```
ubuntu@tegra-ubuntu:~$ rostopic echo /m100_x3/image_raw
```

What am I misssing here? Everything works fine when I do things not through ssh.

**Comment by groundmelon** [comment]
Did you disable lightdm? If not, have a try.

**Comment by andre-nguyen** [comment]
You we're right, disabling lightdm solved it.
