### ISSUE TITLE
Manifold server install issues

### ISSUE THREAD

**Issue by uwleahcim** [groundmelon/m100_x3#3]
I installed the Steps For System Service and Client Type onto my Manifold via the instruction in the Readme. However, the install seems to have messed up my system. The manifold boots into white terminal screen under root user. The command startx fails to start the GUI. I get Fatal server error: (EE) AddScreen/ScreenInit failed for driver 0.

Apparently the server script does start as the video stream is displayed on my mobile DJI GO app. 

When I disable the automatic server startup via editing /etc/init/x3server.conf, in start on item, change [!06] to [!0123456], my system boots up into the GUI login splash screen. However, I can't login. Upon entering the password, the screen blacks out and I'm back at the login splash page. Also make uninstall does not fix the issue.

**Comment by uwleahcim** [comment]
On a re-flash I ran into the same issue (I installed the Manifold Cam library, but had not installed the server client setup yet). I was able to solve the issue by re-enabling lightdm via runlevel [!06] to runlevel [!026] and fixing .Xauthority permission. 

cd /home/ubuntu
mv .Xauthority .Xauthority.old
touch .Xauthority
chown ubuntu:ubuntu .Xauthority

I'm going to install the server client setup now. Keeping my fingers crossed.

**Comment by groundmelon** [comment]
Once you've disabled lightdm (/etc/init/lightdm.conf: runlevel [!026]), you cannot get into GUI. You have to re-enable lightdm(runlevel[!06]) again to get into GUI.

I guess that the image process code has some relationship with HDMI output rendering, so if HDMI is not plugged in, there might be some problem with the code, unless you disable lightdm and set DISPLAY to 0.

If you want to use GUI, always plug in a monitor with Manifold when you need to get the images. If you want to get images without a monitor plugged in, then never try to get into GUI.

And I guess that the problem of .Xauthority permission is you use `sudo startx`?

**Comment by uwleahcim** [comment]
I have lightdm enable (/etc/init/lightdm.conf: runlevel [!06]) (typo in previous post).

Anyways, I'm able to boot into the GUI if I disable the x3server from starting (/etc/init/x3server.conf: [!0123456]). Otherwise, with s3server starting (/etc/init/x3server.conf: [!06]), I boot into a white terminal and error messages in my virtual terminal (Ctrl+Alt+F1)

tegra-ubuntu login: XIO: fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
    after 7 requests (7 known processed) with 0 events remaining.
...
...
(EE)
Fatal server error:
(EE) Server is already active for display 0
      If this server is no longer running, remove /tmp/.XO-lock
      and start again

When I do prevent the x3server from starting on boot and get into the GUI, I can manually start the x3server with 

sudo service x3server start

However, the ros m100_x3_client_node isn't able to connect to the manually started x3server. Now if I start x3server at start with no GUI, I can load m100_x3_client_node and have it connect to the server.

**Comment by groundmelon** [comment]
x3server is not compatible with lightdm. 

With enabled lightdm, you can only use https://github.com/groundmelon/m100_x3#if-you-want-to-streaming-video-from-x3-to-manifold-with-a-hdmi-screen

**Comment by uwleahcim** [comment]
Thank you. I guess I'll do testing with m100_x3_node with the GUI enable.

For actual deployment I'll switch to loading x3server at start and auto starting m100_x3_client_node (should work the same since the topics published are the same correct?)

**Comment by groundmelon** [comment]
topic can be remapped using roslaunch

**Comment by uwleahcim** [comment]
I just have one more question. Since the server/client method uses tcp, would it be feasible to convert to work on udp (reduce latency) and have the server (manifold) send image to the client (some other pc connected by Ethernet to the manifold)?

**Comment by groundmelon** [comment]
Do whatever you want. By the way, latency from camera to Manifold is much more than tcp/udp.
